-- MySQL Script generated by MySQL Workbench
-- Thu Mar  2 11:16:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema summerSchools
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema summerSchools
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `summerSchools` DEFAULT CHARACTER SET utf8 ;
USE `summerSchools` ;

-- -----------------------------------------------------
-- Table `summerSchools`.`anouncement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summerSchools`.`anouncement` (
  `anouncement_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto generated primary key for an anouncement.',
  `anouncement_text` LONGTEXT NOT NULL COMMENT 'The text of the announcement.',
  `anouncement_date` DATETIME NOT NULL DEFAULT NOW() COMMENT 'Date that the announcement is made.',
  PRIMARY KEY (`anouncement_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `summerSchools`.`general_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `summerSchools`.`general_info` (
  `general_info_id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto generated primary key for an anouncement.',
  `general_info_text` LONGTEXT NOT NULL COMMENT 'The text of the announcement.',
  PRIMARY KEY (`general_info_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
